commands:
  global:
    chat_input:
      - name: "echo"
        description: "Re-sends the selected message into the channel you pick."
        options:
          - type: 3
            name: "message"
            description: "The message that should be echo'd. Must be a Message ID."
            required: true
            autocomplete: true
          - type: 7
            name: "channel"
            description: "Where the message will be sent."
            channel_types: [0, 5, 11, 10, 12, 13, 15, 16]
            required: true
          - type: 3
            name: "thread_name"
            description: "Thread name, if message is going into a forum."
            required: false
#          - type: 5
#            name: "preview"
#            description: "Whether you'd like to preview the echo before sending it to the correct channel."
#            required: false
        default_member_permissions: "32"
        contexts: [0]
    message:
      - name: "Echo Message"
        default_member_permissions: "32"
        contexts: [0]
    user: {}

components:
  collab_modal:
    title: "Collaboration Form"
    custom_id: "collab_form_submit"
    components:
      - type: 1
        components:
          - type: 4
            style: 1
            label: "Contact Email"
            placeholder: "example@example.com"
            required: true
            custom_id: "contact_email"
            max_length: 320
      - type: 1
        components:
          - type: 4
            style: 1
            label: "What is the name of your project?"
            placeholder: "Cool project name here!"
            required: true
            custom_id: "project_name"
            max_length: 1000
      - type: 1
        components:
          - type: 4
            style: 2
            label: "Please describe your Project."
            placeholder: "Cool project description here..."
            required: true
            custom_id: "project_description"
      - type: 1
        components:
          - type: 4
            style: 2
            label: "What sort of collab do you have in mind?"
            placeholder: "Really cool collab idea here..."
            required: true
            custom_id: "collab_request"
  support_ticket_modal:
    title: "Support Form"
    custom_id: "support_form_submit"
    components:
      - type: 1
        components:
          - type: 4
            style: 1
            label: "Subject"
            placeholder: "Why are you reaching out?"
            required: true
            custom_id: "support_subject"
            max_length: 500
      - type: 1
        components:
          - type: 4
            style: 2
            label: "Description"
            placeholder: "Explain in detail your issue."
            required: true
            custom_id: "support_description"
            max_length: 3000
  support_close_modal:
    title: "Close Reason"
    custom_id: "support_close_reason_"
    components:
      - type: 1
        components:
          - type: 4
            style: 2
            label: "Reason"
            placeholder: "Reason for closing the ticket."
            required: true
            custom_id: "close_reason"
            max_length: 1000
