commands:
  global:
    chat_input:
      - name: "echo"
        description: "Re-sends the selected message into the channel you pick."
        options:
          - type: 3
            name: "message"
            description: "The message that should be echo'd. Must be a Message ID."
            required: true
            autocomplete: true
          - type: 7
            name: "channel"
            description: "Where the message will be sent."
            channel_types: [0, 5, 11, 10, 12, 13, 15, 16]
            required: true
          - type: 3
            name: "thread_name"
            description: "Thread name, if message is going into a forum."
            required: false
#          - type: 5
#            name: "preview"
#            description: "Whether you'd like to preview the echo before sending it to the correct channel."
#            required: false
        default_member_permissions: "32"
        contexts: [0]
    message:
      - name: "Echo Message"
        default_member_permissions: "32"
        contexts: [0]
    user: {}
