rules_message: |-
  ~~--------------------~~
  **Rule #1:** Please be generally respectful to others, and constructive during conversation.
  **Rule #2:** No posting inappropriate content, such as nudity, gore or anything adult-themed.
  **Rule #3:** No advertising, unless it is your own personal game stream.
  **Rule #4:** Please keep all off-topic conversation in #shartposting, and stick to conversation related to the channel title.
  **Rule #5:** No harmful code, applications or links.
  **Rule #6:** No posting of user data or phishing for user data.
  **Rule #7:** Absolutely no racist, homophobic, sexist or xenophobic terms, slurs, vernacular or epithets of any type within conversation or usernames.
  **Rule #8:** Please speak English. If you cannot speak English, please ask for patience and help with translating.
  We enforce the Discord Guidelines as additional server rules, see here: <https://discord.com/guidelines>
  **These rules apply to all content posted as well as your nickname, avatar, profile, links, and so on.**
  ~~--------------------~~

  :warning: We reserve the right to mute, ban, or kick anyone, at any time, for any reason whether it is listed as a rule above or not.
  :warning: These rules may change from time to time, and we reserve that right, but they will always be displayed in this channel.
  :heart: This server is meant to encourage fun and a sense of community, and we want you to be a part of that!

agreement_message: |-
  I have read the Survivor's Creed, or it was read to me, and I agree to abide by the rules of this Discord Server.  

# title - Article Title
# url - Article URL
# author - Who wrote the article
# timestamp - Timestamp as an int to be used in Discord's auto-formatter

rss_news_message: |-
    :newspaper: | **[{title}](<{url}>)** {author} (<t:{timestamp}:R>)

    ** {url} **

pickup_message_template: |-
    Here you will find all the active Pick-Up-Games!

    A few things to note about the games found here:
    1) There will only ever be game active per region at a time.
    2) Once a game is listed, and at least one other player joins, a voice channel will be made for the game.
    3) XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    In order to start your own game, click the button below and answer the prompts that follow!

# host_id - The id of the current pickup game "host"
# game_region - The region the game is listed to take place in
# server_info - Uses the template named "pickup_chat_server_information"
# expire_timestamp - Timestamp as an int to be used in Discord's auto-formatter

pickup_chat_channel_message_base: |-
    Hello, and welcome to your Pickup-Game Chat! Here are the game details:
    **Host**: <@{host_id}>
    **Region** `{game_region}`{server_info}

    This channel will automatically expire at <t:{expire_timestamp}:t> (<t:{expire_timestamp}:R>). A prompt will appear <t:{action_time}:R> if you need to extend the time.

    *To edit the game settings, please click one of the buttons below!*

# server_name - Name of the server
# server_password - Password of the server
pickup_chat_server_information: |-

    **Server Information**:
      __Server Name__: `{server_name}`
      __Server Password__: ||`{server_password}`||

pickup_pregame_confirm_server_info: |-
    **Selected Region**: {region}
    **Server Information**:
      __Server Name__: `{server_name}`
      __Server Password__: ||`{server_password}`||

    Is all of the above correct?

creed_agreement_failed: |-
  You have attempted to sign using another name.
  Signing the creed has failed.
  You may try again.
